### ISSUE TITLE
User can view existing characters

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/InjusticeDB#1]
## 🖼️ Wireframes

<img width="630" alt="Screen Shot 2021-11-02 at 12 14 35 AM" src="https://user-images.githubusercontent.com/84432043/139802063-75c7a369-1872-4caa-a77e-084be4360735.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create Database to postreSQL
- [x] Import Database to postreSQL

### ☁️ Server

- [x] Handle GET requests for '/api/characters' to load characters from the database

### ⚡ Client

- [x] Create a component for the header 
- [x] Create a component create component for view characters

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
