### ISSUE TITLE
User can view a list of moves for a character

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/InjusticeDB#2]
## 🖼️ Wireframes

<img width="868" alt="Screen Shot 2021-11-02 at 12 17 49 AM" src="https://user-images.githubusercontent.com/84432043/139805912-73edf768-3ec1-469c-8694-008cfa7684cb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add move data to the DB 

### ☁️ Server

- [x] Handle GET requests for /api/characters/:characterId' to load character information from the database

### ⚡ Client

- [x] Create new page for hash routing for characters clicked 
- [x] Create component to display move list data chart

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
