### ISSUE TITLE
User can go back to viewing all characters 

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/InjusticeDB#4]
## 🖼️ Wireframes

<img width="692" alt="Screen Shot 2021-11-02 at 12 18 44 AM" src="https://user-images.githubusercontent.com/84432043/139807230-5341fa11-1bd6-4818-8278-28adf6607d3e.png">

<img width="630" alt="Screen Shot 2021-11-02 at 12 14 35 AM" src="https://user-images.githubusercontent.com/84432043/139807300-a928ee84-a479-4344-b375-e7270e61f00a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to navaigate back to the character screen

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
