### ISSUE TITLE
User can create new move set data for character they choose 

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/InjusticeDB#5]
## 🖼️ Wireframes
<img width="692" alt="Screen Shot 2021-11-02 at 12 18 44 AM" src="https://user-images.githubusercontent.com/84432043/139806199-29000736-f296-49c1-92da-456fe6d279b7.png">

<img width="713" alt="Screen Shot 2021-11-02 at 12 19 35 AM" src="https://user-images.githubusercontent.com/84432043/139806289-af902549-4e0f-4170-be4b-7134551f613c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Handle POST requests for /api//move' to load character information from the database

### ⚡ Client

- [x] User clicks on app drawer
- [x] When user clicks on "create new move set" open a modal of a form
- [x] Create a component to accept a form users fill out to update DB 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
