### ISSUE TITLE
User can delete a move set

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/InjusticeDB#6]
## 🖼️ Wireframes
<img width="692" alt="Screen Shot 2021-11-02 at 12 18 44 AM" src="https://user-images.githubusercontent.com/84432043/139808774-81f3b9bf-852f-46cb-a893-0478b1bea5a4.png">

<img width="715" alt="Screen Shot 2021-11-02 at 12 20 15 AM" src="https://user-images.githubusercontent.com/84432043/139808884-67060794-4248-4db6-b708-d9efe4798781.png">

<img width="646" alt="Screen Shot 2021-11-02 at 12 20 56 AM" src="https://user-images.githubusercontent.com/84432043/139808920-8b78a3f7-e5f0-480c-ba83-7c289b9f8f11.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Test to delete from move tables using the characterId and the move name or the moveId

### ☁️ Server

- [ ] Handle DELETE requests for /api//move' to remove character information from the database

### ⚡ Client

- [ ] Create a component to that will pull up a form modal that will allow the user to delete information from the database
- [ ] On submit close modal

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
